const heading = React.createElement(
  "h1",
  { id: "heading", title: "Heading", className: "heading" },
  "Hello world from React"
);

console.log(heading);
// This console will print the heading object generated by React after using the React.createElement method.
// So whenever we are using the React.createElement method then it will be generating the object not the HTML elements.

const parent = React.createElement(
  "div",
  { className: "parent" },
  React.createElement("div", { className: "child" }, [
    ,
    React.createElement("h1", { id: "heading" }, "This is the h1 Tag"),
    React.createElement("h2", { id: "heading" }, "This is the h2 Tag"),
  ])
);
// If we need multiple children elements then we need to create and array including all the children as above.

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(heading);

// here with the use of render method the V8 engine will automatically convert the object generated by React.createElement into the HTML elements and hence they will be displayed on the screen.
